﻿name: Publish Library

# When a release is published
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: windows-latest

    env:
      VERSION: ${{ github.event.release.tag_name }}

    steps:
    - uses: actions/checkout@v4
    - name: Get version
      run: |
        echo "Building with ${{ env.VERSION }}"
    - name: Build & Push
      run: |
        dotnet build --configuration Release ./RNNoise.NET/RNNoise.NET.csproj -p:Version=${{ env.VERSION }}
        dotnet pack --output nupkgs --configuration Release ./RNNoise.NET/RNNoise.NET.csproj -p:Version=${{ env.VERSION }}
        dotnet nuget push .\nupkgs\*.nupkg -k ${{ secrets.NUGET_TOKEN }}  --source https://api.nuget.org/v3/index.json
